name: vscope
dependencies:
- appnope=0.1.0=py27_0
- backports_abc=0.4=py27_0
- cycler=0.9.0=py27_0
- decorator=4.0.4=py27_0
- freetype=2.5.5=0
- h5py=2.5.0=np110py27_4
- hdf5=1.8.15.1=2
- ipykernel=4.1.1=py27_0
- ipython=4.0.0=py27_1
- ipython-notebook=4.0.4=py27_0
- ipython_genutils=0.1.0=py27_0
- jbig=2.1=0
- jinja2=2.8=py27_0
- jpeg=8d=1
- jsonschema=2.4.0=py27_0
- jupyter_client=4.1.1=py27_0
- jupyter_core=4.0.6=py27_0
- lcms=1.19=0
- libpng=1.6.17=0
- libtiff=4.0.6=1
- markupsafe=0.23=py27_0
- matplotlib=1.5.0=np110py27_0
- mistune=0.7.1=py27_0
- mpi4py=1.3=py27_0
- nbconvert=4.0.0=py27_0
- nbformat=4.0.1=py27_0
- networkx=1.10=py27_0
- notebook=4.0.6=py27_0
- numexpr=2.4.4=np110py27_0
- numpy=1.10.1=py27_0
- openmpi=1.6.3=0
- openssl=1.0.2d=0
- pandas=0.17.1=np110py27_0
- path.py=8.1.2=py27_1
- pexpect=3.3=py27_0
- pickleshare=0.5=py27_0
- pil=1.1.7=py27_2
- pillow=3.0.0=py27_1
- pip=7.1.2=py27_0
- ptyprocess=0.5=py27_0
- pygments=2.0.2=py27_0
- pymongo=3.0.3=py27_0
- pyparsing=2.0.3=py27_0
- pyqt=4.11.4=py27_1
- pytables=3.2.2=np110py27_0
- python=2.7.10=2
- python-dateutil=2.4.2=py27_0
- python.app=1.2=py27_4
- pytz=2015.7=py27_0
- pyzmq=14.7.0=py27_1
- qt=4.8.7=1
- readline=6.2=2
- requests=2.8.1=py27_0
- scikit-image=0.11.3=np110py27_0
- scikit-learn=0.17=np110py27_1
- scipy=0.16.0=np110py27_1
- setuptools=18.5=py27_0
- simplegeneric=0.8.1=py27_0
- singledispatch=3.4.0.3=py27_0
- sip=4.16.9=py27_0
- six=1.10.0=py27_0
- sqlite=3.8.4.1=1
- ssl_match_hostname=3.4.0.2=py27_0
- terminado=0.5=py27_1
- tk=8.5.18=0
- tornado=4.3=py27_0
- traitlets=4.0.0=py27_0
- wheel=0.26.0=py27_1
- xz=5.0.5=0
- zeromq=4.1.3=0
- zlib=1.2.8=0
- pip:
  - alembic==0.8.3
  - backports-abc==0.4
  - backports.ssl-match-hostname==3.4.0.2
  - beautifulsoup4==4.4.1
  - click==6.2
  - dataset==0.6.1
  - ipython-genutils==0.1.0
  - joblib==0.9.3
  - juicebox-etl==0.1
  - jupyter-client==4.1.1
  - jupyter-core==4.0.6
  - mako==1.0.3
  - normality==0.2.4
  - python-editor==0.5
  - pyyaml==3.11
  - redis==2.10.5
  - rq==0.5.6
  - selenium==2.48.0
  - sklearn==0.0
  - sqlalchemy==1.0.9
  - tables==3.2.2
  - tqdm==3.1.4
  - wget==3.2

